### ISSUE TITLE
Ticking entity crash

### ISSUE THREAD

**Issue by Saereth** [TeamDman/ZenTriggers#3]
```
// Surprise! Haha. Well, this is awkward.

Time: 3/5/19 12:36 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at zentriggers.zentriggers.PredicateBuilder.lambda$isInstanceOf$11(PredicateBuilder.java:126)
	at zentriggers.zentriggers.PredicateBuilder.lambda$test$0(PredicateBuilder.java:38)
	at java.util.stream.MatchOps$1MatchSink.accept(Unknown Source)
	at java.util.ArrayDeque$DeqSpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.allMatch(Unknown Source)
	at zentriggers.zentriggers.PredicateBuilder.test(PredicateBuilder.java:38)
	at zentriggers.zentriggers.Handler.lambda$onEntityUpdateRaw$1(Handler.java:25)
	at java.util.HashMap.forEach(Unknown Source)
	at zentriggers.zentriggers.Handler.onEntityUpdateRaw(Handler.java:24)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1089_Handler_onEntityUpdateRaw_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:566)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:181)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

I was just standing next to the enderchickens (3 of them which were submerged in liquid antimatter) and it crashed immediately.

Here is the zenscript i'm using:
```
Handler.onEntityUpdate(	
		PredicateBuilder.create()
			.isInstanceOf(<entity:mightyenderchicken:ent_EnderChicken>)
			.isInBlock(<blockstate:animus:blockfluidantimatter>.block)
			.isNthTick(10)
			.isRandom(0.1)
		,function(event as EntityLivingUpdateEvent){
		val neutron = <avaritia:resource:2>;
		if(isNull(neutron)) {
		print("neutron is null in event");
		return;
		}
		if(isNull(event.entity)){
		print("Entity is null in event");
		return;
		}
		event.entity.world.spawnEntity(neutron.createEntityItem(event.entity.world, event.entity.position));
		event.entityLivingBase.health -= 5;
	}
);
```

**Comment by TeamDman** [comment]
Fixed with .isNotNull() added in 09fa6631f7d61f2c7347860cd5a476ee47b257dd
